apiVersion: apps/v1
kind: Deployment
metadata:
  name: other-nginx-deployment
  namespace: workloads
spec:
  selector:
    matchLabels:
      app: other-nginx
  replicas: 3 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: other-nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
            - containerPort: 80